### ISSUE TITLE
License and author documentation

### ISSUE THREAD

**Issue by nuest** [atmoschem/EmissV#11]
(part of https://github.com/openjournals/joss-reviews/issues/662)

The requirements for the software license are fulfilled, however as a reader I still find it useful to have a reference to the license and the authors in the README file. I suggest to add a short section to the end of the README.

**Comment by nuest** [comment]
You can also use that section in the README to clarify the involvement of the third author listed in `paper.md` (
Edmilson Freitas ) who did not contribute via GitHub (https://github.com/atmoschem/EmissV/graphs/contributors).

**Comment by Schuch666** [comment]
Hi @nuest 
I added the short description of the license and the package

**Comment by nuest** [comment]
My apologies for being unclear, I think it is even better to _not_ repeat legal terms, but just say _"This project is published under the X license."_

In you case

```
EmissV is published under the terms of the MIT License. Copyright (c) 2018 Daniel Schuch.
```

**Comment by Schuch666** [comment]
Thank you @nuest 

I'm no much experience in software documentation

**Comment by Schuch666** [comment]
@nuest updated
