### ISSUE TITLE
Restructure and extend README

### ISSUE THREAD

**Issue by nuest** [atmoschem/EmissV#12]
(part of https://github.com/openjournals/joss-reviews/issues/662)

I suggest to restructure the README file to better align with the required sections:

```
# EmissV

statement of need, in plain language

## Installation

### System dependencies

Ubuntu, Fedora, ...

### Package installation

devtools::...

## Using `EmissV`

[R code chunk]

## ...

[add info about contribution, code of conduct, reporting bugs, seeking support, ...]

## License

...

```

- Can you provide installation instructions for Windows? The Appveyor build works, so I assume a Windows installation is possible. Possibly just mention that no specific steps are needed.
- Regarding the "needed packages"
  - This list will at some point be out of sync with your `DESCRIPTION` file, which is "Good" according to the reviewer guidelines already. I suggest to only list packages here that you actually provide information about, like how/why you import them, what they are needed for - and only if it is not obvious (like sp and raster for geospatial data)
  - "The dependency of the packages spatsts, maptools and sp will be removed son." This is potentially confusing if you do not provide motivation. I suggest to remove this from README and instead create an issue stating that these packages should be removed _any why_.
- For the Example, I suggest you switch to using a `README.Rmd` file to generate the README.md with a R code based example, see http://usethis.r-lib.org/reference/use_readme_rmd.html
- Meta-Information related to _Community guidelines_ are missing, check the ROpenSci GitHub org for examples (such as https://github.com/ropensci/nomisr#meta)

**Comment by nuest** [comment]
I can confirm the system dependency list you have in the README, tested it with Docker using `rocker/r-ver:3.5.0` for Ubuntu and `rhub/fedora-gcc-devel` for Fedora. I was able to install the package when following your installation instructions with [this additional trick](https://gist.github.com/giocomai/0a94e49b3dad053292e73fce7feda411) for `udunits`. Anyway, good job! :100:

Installation on Windows also worked without problems by the way, thanks to the people working hard on Windows binaries.

_Minor comment_: Why do you break up the `yum install` into two commands? I assume it is because the first one is for sf _and_ units and the second one is for netcdf... I recommend following the same structure as for Ubuntu and split the installation up per R package, and add the same comments to Fedora. Right now Fedora users have to make sense of the Ubuntu instructions to understand why they should run the commands.

One further thought:

_What do you think about referencing the installation instructions of `udunits` and `sf` (i.e. https://r-spatial.github.io/sf/#installing) instead of adding them yourself?_ IMHO this has the advantage of not having outdated instructions.

**Comment by Schuch666** [comment]
Hi @nuest 

I updated manually the `README.md` file:
- Added windows installation notes
- Needed packages list (added information and removed some packages)
- Added Contributor code of conduct / Contributing / License
- Link for `udunits` and `sf` installation
- `yum install` updated

I'm reading the `usethis` documentation, is interesting, I will use this package in the future for sure
