### ISSUE TITLE
Add automated tests

### ISSUE THREAD

**Issue by nuest** [atmoschem/EmissV#13]
(part of https://github.com/openjournals/joss-reviews/issues/662)

Strongly recommend to use `testthat` to add tests for the package functionality.
AFAICS the Travis and Appveyor tests only run an installation of the package, but no unit or integration tests. Pointers welcome if I'm wrong!

It is also worth having examples in the docs that actually run (I saw mostly "dontrun" code blocks).

**Comment by Schuch666** [comment]
Hi @nuest , that's right, Travis and Appveyor only test the installation

I am learning how to implement the `codecov` on `EmissV`, [this](https://walczak.org/2017/06/how-to-add-code-coverage-codecov-to-your-r-package) is a good way to do this? I already tried to do this without success.

The examples was updated, now the use of `\dontrun{}` codes are limited to 3 cases:
- The function takes much time (`streetDist` and `lineSource`)
- Plot (no need to test the visualization)
- Functions that require additional files like osm or NetCDF (`streetDist` and `read`)

**Comment by Schuch666** [comment]
100% of `codcov`

**Comment by nuest** [comment]
I've looked at some of the test functions, this is a good start.

I am not a fan of code coverage, so I can't help you there.
