### ISSUE TITLE
Re-check language of examples and comments

### ISSUE THREAD

**Issue by nuest** [atmoschem/EmissV#14]
(part of https://github.com/openjournals/joss-reviews/issues/662)

It's fun to learn some Portuguese and always refreshing to interact with different languages and cultures. However, for the code examples, I suggest to stick to English terms for clarity.

- veiculos: https://github.com/atmoschem/EmissV/search?utf8=%E2%9C%93&q=veiculos

Translating some source code comments might be more welcoming to non-Portuguese contributors, e.g. https://github.com/atmoschem/EmissV/blob/master/R/plumerise.R

**Comment by Schuch666** [comment]
@nuest @benmarwick 

some package examples was updated, accepting new name suggestions for the examples objects names :)

package comments updated, the `plumeRise` was a case of a new function in test phase

**Comment by nuest** [comment]
Why not simply `vehicles_data` ?
