### ISSUE TITLE
read EVERYTHING

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/EmissV#23]
Vamos fazer que EmissV leia TODOS os inventarios disponiveis. 
Eu vou adicionar uma função para baixar os dados tambem.

**Comment by Schuch666** [comment]
Essa já era a minha ideia, estou adicionando aos poucos

**Comment by ibarraespinosa** [comment]
> Essa já era a minha ideia, estou adicionando aos poucos

Very well then!
