### ISSUE TITLE
chemical border conditions

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/EmissV#24]
Oi @Schuch666 

Que tu acha de adicionar aqui, ou no eixport, colocar condições de borde com quimica no wrf_bdy?
A ideia sera ler os dados de um modelo global e mapear os poluentes para o mecanismo quimico, e adicioanr esta informação no netcdf de wrf_bdy. Abs

**Comment by Schuch666** [comment]
É uma ideia, mas acho melhor fazer um outro pacote especialmente para isso

Tem um programa, o [mozbc](https://www2.acom.ucar.edu/wrf-chem/wrf-chem-tools-community), que faz algo nesse sentido (mas só com o modelo MOZART 4, até onde eu sei)
