### ISSUE TITLE
rgdal is retiring soon

### ISSUE THREAD

**Issue by rsbivand** [atmoschem/EmissV#28]
Please protect your package from the forthcoming retirement of **rgdal**: https://r-spatial.org/r/2022/04/12/evolution.html

CMD check on a platform without retiring packages and with `_SP_EVOLUTION_STATUS=2` has this log: 
[00check.log](https://github.com/atmoschem/EmissV/files/9032648/00check.log)

Condition use of **raster** on the the availability of **rgdal** (`raster::projectRaster` fails if **rgdal** is not present), or preferably transition from **raster** to **terra** at your earliest convenience. **terra** is a re-implementation of **raster** but accesses GDAL directly.

**Comment by rsbivand** [comment]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by Schuch666** [comment]
Hi @rsbivand 
Thank you for the note
The `EmissV` R-package has evolving to use less dependencies and the `rgdal` part was replaced to use of other packages
My next step is to replace `raster` but it will take extra time
