### ISSUE TITLE
We need a substitute of anthro_emiss

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/EmissV#9]
I believe we need a substitute of anthro_emiss in EmissV. This tool would allow us to merge/speciate EDGAR and other emissions scenarios/data and use eixport::wrf_create to create wrfcheminputs

**Comment by Schuch666** [comment]
yes

**Comment by Schuch666** [comment]
read() and rasterSource(), functions from EmissV, will have options to do this with few arguments and direct outputs to eixport::to_wrf()
